name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
      	run: pip install -r requirements.txt

      - name: Validate YAML
      	run: yaml-resume validate resume.yml

      - name: Build HTML file
      	run: yaml-resume export resume.yml -e html -t material -i picture.png -o html/index
