name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'resume.yml'
      - 'picture.jpg'
  pull_request:
    branches: [ main ]
    paths:
      - 'resume.yml'
      - 'picture.jpg'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate YAML
        run: yaml-resume validate resume.yml
      - name: Build HTML file
        run: |
          mkdir docs
          yaml-resume export resume.yml -e html -t material -i picture.jpg -o index
          sed -i -s 's/src="file:.*yaml-resume/src="/g' index.html
      - name: Commit
        run: |
          git add index.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true